### ISSUE TITLE
Optional BIP39 passphrase at wallet creation and restore

### ISSUE THREAD

**Issue by tdroxler** [alephium/desktop-wallet#17]
In order to secure a bit more the mnemonic, we can already do it in the backend https://github.com/alephium/alephium/blob/975b343312a0513d3023399d4761f7ba0fb11fb5/wallet/src/main/scala/org/alephium/wallet/api/model/WalletCreation.scala#L26 basically this passphrase change the seed for a given mnemonic. So if someone steal the 24 words, he would still need to know that passphrase.

**Comment by polarker** [comment]
I am a bit against this proposal. I think that creation should go without a mnemonic and restorisaztion should go with a provided mnemonic always. Am I missing anything?

**Comment by nop33** [comment]
@tdroxler you are referring to the so-called 25th word (aka passphrase) which given the 24 words it creates a new wallet, correct? (similar to Ledger: https://www.ledger.com/academy/passphrase-an-advanced-security-feature)

Since this would be an advanced feature, an idea would be that it doesn't need to be part of the wallet creation workflow. It could be found in the settings of the wallet (same as in Ledger).

**Comment by polarker** [comment]
Sorry, forgot my brain fart 😓 It was about mnemonic passphrase!

**Comment by nop33** [comment]
I have many questions on how to implement this!

Supposing we want a similar implementation as [Ledger's hardware wallet](https://www.ledger.com/academy/passphrase-an-advanced-security-feature), where using a passphrase essentially "unlocks" a new wallet.

## Creating a passphrase

I suggest that the creation of a passphrase takes place *AFTER* the initial wallet has been created.

| Step 1 | Step 2 |
| ------ | ------ |
| We could add a button in the "Accounts Settings" modal | Clicking the button will open another modal. Here, the user enters their passphrase and the password that they can use to log in to their wallet. |
| ![image](https://user-images.githubusercontent.com/1579899/148803472-02b72f41-1940-4d33-98a4-31be6110f68b.png) | ![image](https://user-images.githubusercontent.com/1579899/148804335-318c0d50-5475-4b95-938f-28666f9ab49d.png) |

## Accessing the new wallet

Nothing changes here. The user can simply choose their normal account and enter the new password which will unlock the new wallet.

## Restoring wallet with passphrase

I haven't thought this one through yet, but I think having the above things implemented is enough. All the user has to do to restore a wallet with 24 words + a passphrase is to:
1. Restore the wallet normally, using their 24 words
2. Access the Accounts Settings page
3. Attach their passphrase and create a new password
4. Access the wallet

Attaching the same passphrase to the same 24 words should generate the same wallet, right? It's deterministic.

## Blog post

I think it makes sense to write a blog post to explain it, similar to [Ledger's one](https://www.ledger.com/academy/passphrase-an-advanced-security-feature).

**Comment by polarker** [comment]
@nop33 As far as I see, the article is about the theory side, not about implementation. Could you check how it's implemented in Ledger? Shall we copy Ledger? How is other desktop wallet supporting passphrase?

**Comment by polarker** [comment]
Please checkout with Thomas on wallet design details. The ataching thing proposed is not doable as far as I see

**Comment by nop33** [comment]
> As far as I see, the article is about the theory side, not about implementation.

Sorry @polarker, I meant to post this article with the step by step process: https://support.ledger.com/hc/en-us/articles/115005214529-Advanced-passphrase-security?docs=true

**Comment by nop33** [comment]
After discussing several security and UX approaches with @tdroxler & @mvaivre, we agreed that we want to find the sweet spot between high security and great UX. What we want is:

1. Help users protect themselves in case their 24 words get stolen
2. Help users protect themselves in case of threat (5$ wrench attack) to reveal 24 words and passwords (give them the benefit of [plausible deniability](https://bitcoins.net/faq/plausible-deniability))
3. Not confuse users with complicated UI and UX

## User flows

### Creation of account user flow

When creating a new account, the user has the option to secure this account with an optional passphrase. Passphrase input is hidden behind an “advanced options” expandable section (ie. complexity is hidden by default).

### Login user flow

The login screen allows the user to:
- Choose the account they want to login
- Enter their password
- Optionally enter a passphrase

#### Login Scenarios
1. If a passphrase **does not exist** for this account and the user **does not enter a passphrase**, the wallet unlocks (current flow).
2. If a passphrase **does not exist** for this account and the user  **enters a passphrase**, an error message saying *"No account associated with this passphrase"* appears.
3. If a passphrase **exists** for this account and the user **enters the correct passphrase**, the passphrase-enabled-wallet unlocks.
4. If a passphrase **exists** for this account and the user **enters a wrong passphrase**, an error message saying *"No account associated with this passphrase"* appears. It is important to **not** say _"Wrong passphrase"_ because this defeats the benefit of plausible deniability, by revealing that the user **has used** the passphrase optional feature and **cannot deny it**.
5. If a passphrase **exists** for this account and the user **does not enter a passphrase**, the "decoy" wallet unlocks. The user can decide whether they want to load some small funds to the decoy wallet or not.

### Wallet restore/import user flow

- When importing a wallet using the mnemonic 24 words, the user has the option to provide a passphrase as well.

## Security & UX considerations

### Higher security

Some of the desktop wallets that I have tested (Wassabi wallet, Coinnomi wallet) allow that if you enter a different passphrase, a new empty wallet will be created.

Even though this is the best approach regarding security, we do not like it, because we are afraid that it will confuse our users a lot (aka "Where did my funds go, I think my passphrase is correct?").

Ledger and other hardware wallets allow the association of **multiple passphrases** to the same set of 24 words. We think that even though this increases security a lot, it will complicate the UX and UI. Thus, we agree to allow 1 passphrase per wallet.

### Least confusing UX

The least confusing UX would be to **not allow** a passphrase-enabled-wallet to unlock a "decoy" wallet when no passphrase is entered at login, and instead show a message "Please, enter the passphrase associated with this account".

If we do that, however, we cannot give the user the benefit of plausible deniability (Requirement 3) and they can easily become victims to the 5$ wrench attack.

## How other desktop wallets implement BIP39 with passphrase

<details><summary> Electron wallet</summary>

### Electon wallet creation user flow

| Give a name | Choose type | Choose create | Click "Options" and "Extend with custom words" | Enter passphrase |
| ------------ | ------------- | -------------- | ------------------------------------------------- | ----------------- |
| ![image](https://user-images.githubusercontent.com/1579899/148951915-7cce44dc-ec93-404d-b64a-7c3e0ab7e199.png) | ![image](https://user-images.githubusercontent.com/1579899/148952002-bde6674e-9598-454d-9569-b20db40e8489.png) | ![image](https://user-images.githubusercontent.com/1579899/148952124-b068d599-7258-4e4d-a2f3-b6062d12bc4d.png) | ![image](https://user-images.githubusercontent.com/1579899/148952500-b4024983-db23-4b4f-b8f7-4cdbf821f51c.png) | ![image](https://user-images.githubusercontent.com/1579899/148952594-be05e637-084d-48b2-beff-c710ab81373c.png) |

### Electron wallet restoration user flow

| Give a name | Choose type | Choose "I have seed"  | Enter seed | Click "Options" and "Extend with custom words" | Enter passphrase |
| ------------ | ------------- | ---------------------- | ----------- | ------------------------------------------------- | ----------------- |
| ![image](https://user-images.githubusercontent.com/1579899/148951915-7cce44dc-ec93-404d-b64a-7c3e0ab7e199.png) | ![image](https://user-images.githubusercontent.com/1579899/148952002-bde6674e-9598-454d-9569-b20db40e8489.png) | ![image](https://user-images.githubusercontent.com/1579899/148952729-332cd33a-89a6-41fd-ada7-6cf65a141ce5.png) | ![image](https://user-images.githubusercontent.com/1579899/148952898-ace900cf-f8c6-4049-92bf-6e03355d57fd.png) | ![image](https://user-images.githubusercontent.com/1579899/148952946-c0e27e34-9b2c-4da4-8b61-6a266754eedf.png) | ![image](https://user-images.githubusercontent.com/1579899/148952988-c58ed651-9c42-4625-856f-e38220b946e2.png) |
</details>

<details><summary>Coinomi wallet</summary>

They only allow restoration with a passphrase (no creation)

<img width="1136" alt="Screenshot 2022-01-11 at 13 27 38" src="https://user-images.githubusercontent.com/1579899/148955574-e8cffe90-469b-48b6-abcd-798afd7ad26f.png">

</details>

<details><summary>Wasabi wallet</summary>

They called it "wallet password" and you cannot have a wallet without it.

### Wasabi wallet creation user flow

| Enter name and passphrase |  Confirm |
| ---------------------------- | -------- |
| <img width="1212" alt="Screenshot 2022-01-11 at 09 12 40" src="https://user-images.githubusercontent.com/1579899/148956070-eff45d9f-6ca0-4b47-83a1-b8b9a68625d9.png"> | <img width="1212" alt="Screenshot 2022-01-11 at 09 23 05" src="https://user-images.githubusercontent.com/1579899/148956104-70d32fb9-f63c-466e-ab27-1ac4484188cb.png"> |

### Wasabi wallet restoration user flow

<img width="1212" alt="Screenshot 2022-01-11 at 09 12 46" src="https://user-images.githubusercontent.com/1579899/148956274-ede5fa0b-4b50-48ba-b4b5-41c7c9c8ddac.png">

</details>

**Comment by polarker** [comment]
@nop33 LGTM. Please chat with @tdroxler regarding how to store and verify passphrase

**Comment by tdroxler** [comment]
@polarker yep we discussed it yesterday too, we will use the same double hash as in the node. The seed won't be store anymore in the secret file either and will be computed on creation/restore/unlock and store in memory. We will now have the same level of security as in the node, maybe even more as we well have this "decoy" wallet, which I found a great idea, maybe we could do the same in then node.

@nop33 Awesome work and resume, it's also super sweet to have all the screenshots of others wallet! Great investigation :rocket:

**Comment by nop33** [comment]
Since this task is not the highest priority anymore, I am unassigning myself. Happy to work on it when again whenever possible!

**Comment by polto** [comment]
Sorry guys, it took me only one month to get back to this issue and read the thread. 

Normally following BIP39 there is not way to have "wrong passphrase" every possible passphrase will derive a new valid HD wallet tree. can be empty, but still valid.

With a passphrase you may be trying to protect against someone finding your 24 words (the passphrase should also be backedup, but elsewhere), but you may also try to protect against passphrase extraction from your device (such as trezor, so you simply don't record it in the device, only temporary use it and have to setup it again after each reboot of the hardware wallet)

Just to make sure decoy wallet can be the main (24 words) , but can also be 24 + passphrase, can be both also, and one can have multiple decoy passphrases, or even separations of segregated wallets via a specific passphrase.

All of this is covered by BIP39 and if we want interoperability with other wallets we should closely follow the standard. 

For example I have often seen the use of a segregated wallet with 24 words + passphrase, then the user switch to another segregated wallet using a different passphrase with the same 24 words.

The passphrase is either not stored in the encrypted file on the device at all, or is stored, but associated to a different pin (on ledger or trezor or coldcard for example). Usually you first setup the 24 words, then in the advanced options there is a way to add a passphrase to re-derive the HD wallet(s) 

I have tested and am using a lot of different wallets with passphrase support, I am happy to test the UI/UX and/or to chat about this features.

**Comment by mvaivre** [comment]
@polarker Do you think that now is a good time to look into this? IMO, this would be a great way to increase security before supporting hardware wallets. WDYT?

**Comment by tdroxler** [comment]
oh yes, I will finally be able to use my address with the desktop wallet :)

**Comment by polarker** [comment]
@mvaivre yeah, it's good to have it if we don't have other priorities.

As far as I know, there are two approaches to support this:
1. add an optional passphrase for each wallet and ask users to provide the passphrase every time users access the wallet. In this approach, the passphrase is stored in the secret file.
2. each wallet can use any passphrase, and we don't store the passphrase in the secret file. The passphrase is only required when unlocking the wallet.

We will need to decide which approach to go. The second approach is more popular, but it has user experience issues because there is no way to tell if the passphrase is correct or not.

@polto correct me if I am wrong.

**Comment by nop33** [comment]
FYI, we have 3 requirements for this task: https://github.com/alephium/desktop-wallet/issues/17#issuecomment-1009992481

**Comment by polarker** [comment]
Thanks for the info.

It's close to the first approach I mentioned. I personally like it, but as I mentioned the second approach is more popular. I don't have any strong opinions.

**Comment by polarker** [comment]
For example, I believe Ledger should be following the second approach. I don't have that much time to argue about the details. @polto should be able to help I think.

**Comment by lf94** [comment]
Note: The feature is moving forward using the proposal. No longer in investigation.

**Comment by LeeAlephium** [comment]
Note: The feature moved forward without following the proposal. See the PR for details if you're from the future reading this :)
