### ISSUE TITLE
Replace the "ALEF" utf8 symbol with a SVG

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#176]
For consistency sake across OSes. As of today, the symbol is rendered in very different ways.

Note: this component could later be shared in a "common" UI library.

**Comment by lf94** [comment]
A small example I wrote https://jsfiddle.net/rkx4m1qc/ .

This solves the problem of:

1. rendering the ALEF symbol consistently (we will use an SVG) and
2. copying a consistent identifier (ALPH)

**Comment by nop33** [comment]
Nide idea @lf94 and good job! So, what are we missing to implement this and close this issue? The SVG and the React component?

**Comment by mvaivre** [comment]
Let's use [this one](https://commons.wikimedia.org/wiki/File:Hebrew_letter_alef_freefonts.svg), to see how it looks.

**Comment by nop33** [comment]
There are multiple places where we use the ℵ character:
1. `Amount` component
2. Form input placeholders:
   1. [`AmountInput`](https://github.com/alephium/desktop-wallet/blob/556d1548bad35f30e51798b5435a8710e85d361e/src/components/Inputs/AmountInput.tsx#L72)
   2. [`TransactionForm` gas price input](https://github.com/alephium/desktop-wallet/blob/f327f46279b166bd8487cb3fdc5ddc928ee195b4/src/modals/SendModal/TransactionForm.tsx#L134)
3. `InfoBox`s:
   1. [`CheckTransaction`](https://github.com/alephium/desktop-wallet/blob/761c3958db7512ab6491e5b8533618b7317d3c4d/src/modals/SendModal/CheckTransaction.tsx#L45-L46)
   2. [`TransactionForm`](https://github.com/alephium/desktop-wallet/blob/f327f46279b166bd8487cb3fdc5ddc928ee195b4/src/modals/SendModal/TransactionForm.tsx#L120)
4. Form error messages: [`TransactionForm` gas price](https://github.com/alephium/desktop-wallet/blob/f327f46279b166bd8487cb3fdc5ddc928ee195b4/src/modals/SendModal/TransactionForm.tsx#L81)

---

1. I updated the `Amount` component to use the SVG from Wikipedia. I had to play a bit with the SVG code to get it right. I created 2 SVGs for the 2 themes we have, cause I can't figure out how to edit the color of an SVG that is used as a background image. Alternatively we could possibly achieve that by rendering the SVG instead, but that would pollute the DOM a lot... Here's the code: https://github.com/alephium/desktop-wallet/commit/4c8a3892dd196851e051471be02f0d278f0933cf
2. That will be tricky to do, since we cannot render HTML elements inside the `placeholder` attribute of an `input` element.
3. For `InfoBox`, I would have to change the `text` attribute to be able to receive DOM elements (or use `children` instead of `text`).
4. That will also require some refactoring of the code to support SVGs.

**Comment by lf94** [comment]
In the places where we have N in a placeholder, we can move it to outside the textbox? It may be more consistent this way since N is not retained on typing.

Thank you for the breakdown of problems. I think we should do whatever we have to do (in this case, some refactoring as you said)...!
