### ISSUE TITLE
Init i18n

### ISSUE THREAD

**Issue by mvaivre** [alephium/desktop-wallet#192]
Translating the wallet would increase accessibility and broaden the potential audience of the app.
It's a relatively low hanging fruit, easy to implement using for instance [react-i18next](https://react.i18next.com/).

It would also be a wonderful opportunity to involve our community to provide translations (cc/ @Sakrecoer )

**Comment by Sakrecoer** [comment]
Thanks for cc:ing me! I applause the initiative and agree with the benefits! It will be a pleasure to help make this happen!

**Comment by nop33** [comment]
I suppose then that all English texts from the wallet would live inside a yaml or json file, right? Then, maybe we could find some tools that integrate with GitHub and allow the community to easily make PRs to add translations! win-win!

**Comment by lf94** [comment]
It'd be better to use more official internationalization technology like `gettext`: https://en.wikipedia.org/wiki/Gettext
It's fairly ubiquitous.

**Comment by nop33** [comment]
I don't know what tools are out there, I would need to do research. But first, we gotta define our requirements. I would propose the following requirements, please, feel free to extend:
1. Good integration with React
2. We can easily involve the community in adding translations (there are easy to use tools available for non-tech people)

**Comment by mvaivre** [comment]
As said in the description, I had some good experiences with [react-i18next](https://react.i18next.com/)! It's lightweight, straightforward, ships with a handy `useTranslation` hook, and is based on simple json files. But I'm curious to see of new alternatives exist.

**Comment by LeeAlephium** [comment]
Well like I said, `po` files are accepted by a lot of translation services, whereas json which can be structured in any way may not be as common (non-standard)... Haven't gotten around to looking at anything but I wouldn't be surprised if react-i18next reads them too or has a tool for conversion :slightly_smiling_face:

**Comment by mvaivre** [comment]
After a quick research, it seems like most of the translation services now support JSON ([this](https://www.codeandweb.com/babeledit), [that](https://localazy.com/multilingual-json), [this one](https://poeditor.com/kb/json-editor), [that one](https://locize.com/) (by the creators of i18next)...), and there are ways to convert [po <-> json](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/commands/json2po.html) if needed. So it seems like we should rather focus on comparing the Devx of the different solutions! 👓

**Comment by LeeAlephium** [comment]
i18next looks just fine then :)

https://www.i18next.com/principles/fallback#key-fallback makes me happy to see, but I'm surprised it's not recommended:

> While this works and might reduce files to load it makes the management of translations a lot harder as you will need to update changes to fallback values in code and JSON files.
> Possible - but not recommended.

I find it's the opposite: people have preferred `po` over time because you don't lose the semantics of what you're translating, and if one is missing it will fallback to the "source of truth" translation (English). Regardless you will have to change key names if the semantics change, which happen all the time, and a short key name is usually not sufficient to capture semantics.

**Comment by nop33** [comment]
When I was working for the open source software [Indico](https://github.com/indico/indico), we were using [Transefix](https://www.transifex.com/) as the service to upload our json files so that translators have a smooth experience in translating them. I remember it offers a [free tier](https://www.transifex.com/open-source/) for open source projects. Might be interesting for us.

Here's a preview of the current localization status of Indico for example: https://www.transifex.com/indico/indico/
