### ISSUE TITLE
Proper derivation paths for accounts / addresses

### ISSUE THREAD

**Issue by polto** [alephium/desktop-wallet#195]
The intent behind multiple addresses in the desktop wallet is to isolate different usages. (mining, DApps, personal, work, ...)

My concern is that for now we derive a bit from the [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) standard terminology and that it may cost us some more work later or bring some bad legacy.

Currently we call `Account` a new **seed** and have  `Addresses` for **different usages** such as for DApps, vault, mining, ...
This is not standard. 

BIP44 propose : `m / purpose' / coin_type' / account' / change / address_index`. Each level has a special meaning.

## account
The `account` level splits the key space into independent user identities, so the wallet never mixes the coins across different accounts. Users can use these accounts to organize the funds in the same fashion as bank accounts; for donation purposes (where all addresses are considered public), for saving purposes, for common expenses etc. Software should prevent a creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before). 

## change 
Constant 0 is used for external chain and constant 1 for internal chain (also known as change addresses). External chain is used for addresses that are meant to be visible outside of the wallet (e.g. for receiving payments). Internal chain is used for addresses which are not meant to be visible outside of the wallet and is used for return transaction change. 

We do not implement this for now. Change is going back to the same address. But we should make sure we use it in a future proof way. 

## address_index
Addresses are grouped per account and wallets are allowed to group UTXOs from several `addresses` of the same `account` into a single transaction.

Even if we do not support the "no address reuse" policy for now - it's good to be compatible with it upfront by following the BIP44. 
____

I  propose to change "Accounts" to "Wallets" as this is the case for example in BlueWallet that supports multiple seeds in the same interface.

And to change what we currently call "Addresses" to "Accounts" and  "generate a new address" into "generate a new account".

**Comment by nop33** [comment]
For what is worth, i have already prepared a fix for that: https://github.com/alephium/js-sdk/commit/ba4ffe3273dfc7dc2f4652ee3a1c6d0d8ec55770

Afk till tomorrow.

**Comment by polto** [comment]
also wallets automatically sum the amounts among all UTXOs of all addresses of the same account. since the usage is delimited per account.

**Comment by lf94** [comment]
I think there is simply a usage issue happening rather than a change in scheme needed, and I believe this is happening because individual addresses can be labeled.

I'll add a more detailed reply much later, but I wanted to say that to maybe get the gears turning about how the UX can change. I'm in full agreement that the current way things are presented, we cannot be doing 1 account -> 1 address, but rather 1 account -> N addresses. When a new account is created we should be incrementing the account slot, and then deriving new addresses we increment the address index.

We need to be careful the derivation scheme also remains consistent with the node backend or else wallet restoration will not be the same.

OK, will write more later!

**Comment by polto** [comment]
Right, In Bitcoin addresses are used as "invoices" to be payed. When you invoiced several payments and have a set of UTXOs they are summed by the wallet per account - used to separate usages.. So even if we do not use multiple addresses per account yet, it's good to be ready for this to happen. 

If you strictly follow BIP44 address discovery every wallet should discover accounts and addresses in the same way.

**Comment by lf94** [comment]
Thanks Cheng!

For those reading: the design motivation documented in BIP44 doesn't match with what's been said: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#motivation
With that said I understand HD wallets have been satisfying one need of deriving new addresses for each transaction for a long while.

I'm tending to agreement that the current BIP44 scheme chosen is sufficient for typical users, but at the same time, using accounts would be very useful for separation of funds within the same seed while still being able to generate new addresses under an account. If we can support BIP44 properly, why not?...

That's my vote. :slightly_smiling_face: I'd like to see what others would like to do so we can bring closure to this discussion. It's important because our mobile-wallet is a greenfield project where we can apply this immediately.

/cc @mvaivre @tdroxler @h0ngcha0 @nop33

**Comment by nop33** [comment]
Well, now it's a bit late. People have already created through the desktop wallet their "separation of funds" addresses whose derivation paths are `1234'/0'/0'/0/X`, not `1234'/0'/X'/0/0`. If we decided to align with BIP44, we would now need to somehow discover and migrate those addresses. This will create a bad UX, cause their addresses will need to change.

**Comment by mvaivre** [comment]
I havent's answered before because we can achieve the same UX with either multi-accounts/single-address (m / 44' / 1234' / accountIndex') or single-account/multi-addresses (m / 44' / 1234' / 0' / 0 / addressIndex). 
So I'm trusting Cheng on this :)

**Comment by lf94** [comment]
Let's stick with the current scheme then. :slightly_smiling_face:
