### ISSUE TITLE
Fix position of toggle icons

### ISSUE THREAD

**Issue by nop33** [alephium/desktop-wallet#209]
Not properly centered

<img width="549" alt="image" src="https://user-images.githubusercontent.com/1579899/163168821-ea95d0ad-782c-4913-95b0-688ba6f19617.png">
<img width="502" alt="image" src="https://user-images.githubusercontent.com/1579899/163168851-78b61186-81ee-45ba-b594-be720ec1f483.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/1579899/163168877-8a9e2815-9650-481f-b4fd-1f98ae76b208.png">

**Comment by lf94** [comment]
Noting the root cause:

The issue here is a 4px margin on each side, making them "squish". 

```
622358e9 (mvaivre            2022-03-17 11:57:47 +0100 144)   margin: 0 ${toggleMarginInPx * 2}px;
```

I think @mvaivre did this because without it, the icons in the theme switcher look wonky depending where the switch is!

A comparison:

Without 4px: ![1651796581](https://user-images.githubusercontent.com/547923/167047254-186d4a99-c407-43b4-8863-372086ad1c21.png)
With 4px: ![1651796483](https://user-images.githubusercontent.com/547923/167047255-d95216d5-965a-4990-aaf4-a805e6a60161.png)


Without 4px: ![1651796617](https://user-images.githubusercontent.com/547923/167047350-03680396-6e78-4890-91ca-25461575f02a.png)
With 4px: ![1651796626](https://user-images.githubusercontent.com/547923/167047348-86896355-6630-4273-8c7a-4d8899386987.png)

It's quite subtle.
