### ISSUE TITLE
Address derivation sometimes diverges between "using for defi" and "generate more addresses" functions

### ISSUE THREAD

**Issue by lf94** [alephium/desktop-wallet#220]
**Describe the bug**
When trying to import my miner seed, I noticed I got 1 of n addresses which actually matched - the rest didn't. This was when I was pressing "generate more addresses".

I re-imported and then used the "using for defi" option, which generated the correct addresses.

**To Reproduce**
I have no idea how to reproduce.

**Expected behavior**
The two methods should have the exact same behavior.

**Screenshots**

![1650460945](https://user-images.githubusercontent.com/547923/164241234-765c79ef-7ddb-4915-ac37-2ed0872bf9e3.png)
![1650460915](https://user-images.githubusercontent.com/547923/164241236-24281e23-9369-4107-b236-3ce401833b4f.png)

**Environment**
 - Version: 1.2.0

**Additional context**

**Comment by nop33** [comment]
"+ Generate new address" button: Increments the `address_index` derivation path level to generate the next available address without leaving any gaps. If the "group" is set to a different than the default one, it will keep incrementing the `address_index` until it finds an address in that group.
Example: The initial address has derivation path `44'/1234'/0'/0/0`.
1. User clicks "+ Generate new address" button, opens the "Advanced options", sees that the group is set to "Group 2" but they don't mind, so they click "Generate". The new address has derivation path `44'/1234'/0'/0/1` (simple +1 increment).
2. User clicks again the "+ Generate new address" button, opens the "Advanced options", sees that the default group is set for "Group 1" and changes it to "Group 0". The new address has derivation path `44'/1234'/0'/0/5`, because that was the next available address in group 0.
3. User clicks again the "+ Generate new address" button, opens the "Advanced options", sees that the group is set to "Group 1" but they don't mind, so they click "Generate". The new address has derivation path `44'/1234'/0'/0/2`, because that was the next available derivation path without leaving any gaps.

The "Generate one address per group " of the "Advanced management" section of the "Addresses" page, as well as the "Advanced user: want to start with one address per group for mining or DeFi?" checkbox in the welcome screen act differently than the "+ Generate new address" button. Those options traverse the incremental derivation paths until one address in each group is found. So, as an example, it might result in:
1. `44'/1234'/0'/0/0`
2. `44'/1234'/0'/0/1`
3. `44'/1234'/0'/0/2`
4. `44'/1234'/0'/0/3`

but it might also result in
1. `44'/1234'/0'/0/0`
2. `44'/1234'/0'/0/4`
3. `44'/1234'/0'/0/7`
4. `44'/1234'/0'/0/15`

**Comment by lf94** [comment]
Thank you for the explanation; actually it's so good we should consider including it in the wiki!

I'll close the issue since it's not a bug.
