### ISSUE TITLE
Font size baseline selector

### ISSUE THREAD

**Issue by Jbashimov** [alephium/desktop-wallet#416]
If possible please put in ALPH wallet font size selector (small, medium, big). In bigger resolution of screen looks very unclear and small without font size select. And if possible put among colors Grey color

**Comment by mvaivre** [comment]
Hey there, thanks for your feedback.
We'll take this into consideration! Accessibility is one of our priorities and in that sense a font size selector could make sense.

**Comment by nop33** [comment]
@mvaivre I am trying to think of ways to implement this... One idea I have is that instead of using `px` values for font-sizes, to use `rem`, so that when the user changes the base font-size, we update the root font size and all rem values update accordingly.

Another idea would be to somehow trigger the zoom level of our app, but then not only the font-sizes but everything becomes bigger (which might not be such a bad idea). This already works now, if the user does `Ctrl`+`+`.

**Comment by mvaivre** [comment]
The baseline font size is increased to 13px in v2.0 (it was 12px before), this will already help a lot to improve clarity.

And you're right, users can easily zoom by using the shortcut, or the item in the menu bar:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/6715943/223800194-dd50422d-885f-405a-9afe-24350540c61a.png">

I'll close this for now, as I believe this can solve the initial issue.
