### ISSUE TITLE
Clickable network

### ISSUE THREAD

**Issue by tdroxler** [alephium/desktop-wallet#503]
When testing the wallet, I definitively wanted to click on the network and was expecting to be able to change the network. Or it could open our setting window to edit the network.

![maim-1675262643](https://user-images.githubusercontent.com/2979182/216074918-efbf54b7-75d5-45da-90ba-0e371705c700.png)

It looks like a button :)

**Comment by mvaivre** [comment]
Yes, this gonna be done in the upcoming v2.0 redesign. New `Select` cursor positioning was added in #492 to make it easy.

**Comment by nop33** [comment]
I propose that when the user clicks on the network badge, a popup appears with the available network options, similar to how the [`Select` component](https://github.com/alephium/desktop-wallet/blob/v2.0/src/components/Inputs/Select.tsx) works. We cannot reuse the `Select` component (since that one is displayed as an input field), but we can def reuse the `SelectOptionsModal`.

The options will be:
- Mainnet
- Testnet
- Localhost
- Custom

When the user clicks any of the first 3, we simply switch the network to the selected preset. If the user clicks on the 4th one, however, we should open the settings modal so that they can configure the endpoints.

WDYT?



![Image](https://user-images.githubusercontent.com/1579899/231221834-df2daadd-85be-47bc-8a1c-46362a895e1c.png)

**Comment by mvaivre** [comment]
Thanks for the suggestion!
I've already done a first implementation in #608 if you want to check. I've reused the Select component. 

I started implementing exactly what you suggested, then I decided that this shortcut could (should?) show only choices that are used the most by non dev users, in order to reduce apparent complexity (ie. I don't show localhost and custom by default).

One thing we could implement though, may be a third "More options" choice, with a little "arrow suffix" with would open the settings modal..

**Comment by nop33** [comment]
I was about to start working on this last night, good thing I didn't and great thing that you already did it 😅 I should have checked the assignee of this task before.

I would suggest we add an "assignee" column in our GitHub project table, WDYT?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1579899/231376095-4ca40841-bbea-4e32-b635-b89819b5854a.png">

**Comment by mvaivre** [comment]
> I would suggest we add an "assignee" column in our GitHub project table, WDYT?

Yes good idea! Done.
